
   
services:
  web:
    build: .
    command: python serve.py
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env