
   
services:
  web:
    build: .
    image: julienzip/jadevine
    command: python serve.py
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    env_file:
      - .env